# Site settings
title: "BioVis 2022"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2022"
url: "http://biovis.net"
conferenceshort: "BioVis 2022"

#FIX ME: the event number is most likely not correct
#eventNum: "12th" 

IEEEconferencedate: "TBA"
IEEEconferenceplace: "TBA"
year: 2022


# Old deadlines so I remember what they're called
# When everything breaks
#IEEE_deadline_submission: "TBD"
#IEEE_deadline_notification: "TBD"
#IEEE_deadline_camera: "TBD"
#IEEE_deadline_poster: "TBD"

ismb_conference_name: "ISMB 2022"
ismb_conference_link: "https://www.iscb.org/ismb2022"
ismb_conference_registration_link: "https://www.iscb.org/ismb2022-register"
ismb_conference_date: "July 10-14, 2022"
ismb_conference_place: "Madison, WI, USA (or virtual)"
ismb_conference_key_dates_link: "https://www.iscb.org/ismb2022-key-dates"

ismb_cosi_date: "July 13, 2022"

ismb_paper_submission_deadline: "January 13, 2022"
ismb_paper_conditional_acceptance: "March 3, 2022"
ismb_paper_revision_deadline: "March 17, 2022"
ismb_paper_final_acceptance: "April 4, 2022"

ismb_talk_submission_deadline: "April 21, 2022"
ismb_talk_acceptance: "May 12, 2022"

ismb_poster_submission_deadline: "April 21, 2022"
ismb_poster_acceptance: "May 12, 2022"
ismb_poster_late_submission_deadline: "May 19, 2022"
ismb_poster_late_acceptance: "May 26, 2022"

ismb_paper_submission_link: "https://www.iscb.org/ismb2022-submissions/proceedings"
ismb_abstract_submission_link: "https://www.iscb.org/ismb2022-submissions/abstracts"

#bmc_submission_deadline: ""
#bmc_conditional_accept: ""
#bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
- posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
lang: en-US
