# Site settings
title: "BioVis 2022"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2022"
#url: "http://biovis.github.io/biovis_2016"
url: "http://biovis.net"
conferenceshort: "BioVis 2022"
#FIX ME: the event number is most likely not correct
eventNum: "12th" 
IEEEconferencedate: "TBA"
IEEEconferenceplace: "TBA"
ISMBconferencedate: "TBA"
ISMBconferenceplace: "TBA"
year: 2022
ismblink: "https://www.iscb.org/ismbeccb2022"

# Old deadlines so I remember what they're called
# When everything breaks
#IEEE_deadline_submission: "TBD"
#IEEE_deadline_notification: "TBD"
#IEEE_deadline_camera: "TBD"
#IEEE_deadline_poster: "TBD"

#ISMB_hl_and_nresearch_submission: "TBD"
#ISMB_deadline_poster: "TBD"
#ISMB_hl_and_nresearch_notiication: "TBD"

ismb_paper_submission_deadline: "TBA"
ismb_paper_conditional_accept: "TBA"
ismb_paper_revised: "TBA"
ismb_paper_final_acceptance: "TBA"

ismb_poster_submission_deadline: "TBA"
ismb_talk_submission_deadline: "TBA"

#ismb_poster_accept: "TBA"
#ismb_poster_oral_notification: TBA"
#biovis_paper_submission_deadline: "TBA"
#ismb_abstract_submission_deadline: "TBA"
#ismb_highlights_submission_deadline: "TBA"
#ismb_highlights_accept: "TBA"

#bmc_submission_deadline: ""
#bmc_conditional_accept: ""
#bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
- posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
